/* HANDFORGED — shell-only service worker (generated by tools/build_mobile.py).

   Caches the shell and NOTHING else. The game is ~400MB of art and audio; it
   streams from the network every session by design. Navigation is
   network-first so an update is never shadowed by a stale index.html, and the
   cache falls back in only when the network is gone. */
const CACHE = 'hf-shell-alpha-0-27-fd80c312';
const SHELL = ["./", "./index.html", "./manifest.webmanifest", "./sw.js", "./icon-192.png", "./icon-512.png", "./apple-touch-icon.png"];
const SCOPE = new URL('./', self.location).pathname;
const SHELL_PATHS = new Set(SHELL.map(function (p) {
  return new URL(p, self.location).pathname;
}));

self.addEventListener('install', function (e) {
  e.waitUntil(caches.open(CACHE)
    .then(function (c) { return c.addAll(SHELL); })
    .catch(function () {})
    .then(function () { return self.skipWaiting(); }));
});

self.addEventListener('activate', function (e) {
  e.waitUntil(caches.keys().then(function (keys) {
    return Promise.all(keys.map(function (k) {
      return k === CACHE ? null : caches.delete(k);   // retire every old build
    }));
  }).then(function () { return self.clients.claim(); }));
});

self.addEventListener('fetch', function (e) {
  const req = e.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;
  const nav = req.mode === 'navigate';
  // ANYTHING THAT IS NOT THE SHELL FALLS THROUGH UNTOUCHED. No respondWith,
  // no cache lookup, no clone: the browser fetches it exactly as it would
  // with no worker installed at all.
  if (!nav && !SHELL_PATHS.has(url.pathname)) return;
  e.respondWith(fetch(req).then(function (res) {
    if (res && res.ok && res.type === 'basic') {
      const copy = res.clone();
      caches.open(CACHE).then(function (c) { c.put(req, copy); }).catch(function () {});
    }
    return res;
  }).catch(function () {
    return caches.match(req).then(function (hit) {
      return hit || (nav ? caches.match(SCOPE + 'index.html') : Response.error());
    });
  }));
});
